<a href="https://colab.research.google.com/github/Samuel2000-Souff/TD_Stat_Rendu/blob/master/TD1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TD 1 | Introduction à Python pour l'analyse de données

---

Objectifs du TD :

* découvrir Python
* se familiariser avec le langage et le notebook Jupyter
* découvrir et maîtriser les bases des librairies de calcul numérique et d'analyse de données numpy et pandas

---

##  Installation de Python et Jupyter

### Windows

#### Installation Python

Vérifiez si vous avez déjà une version de python installée en ouvrant l'invite de commande et en exécutant l'une des deux commandes python suivantes : 
> python --version   

> python3 --version 

Si ce n'est pas le cas, vous pouvez procéder à l'installation comme suit :
 
1. Allez sur le site web : https://www.python.org/downloads/windows/
2. Cliquez sur "Latest Python 3 Release - Python 3.10.7".
3. Si votre ordinateur utilise une version 64 bits de Windows, téléchargez le Windows installer (64-bit). Sinon, téléchargez Windows installer (32-bit).
4. Après avoir téléchargé le Windows installer, vous devez l'exécuter (double-cliquez dessus) et suivre les instructions qui s'y trouvent.

NB : Au début de l'installation, assurez-vous de cocher la case "Add Python 3.10 to PATH" ou "Add Python to your environment variables" avant de cliquer sur "Install Now".


#### Installation Jupyter

Ouvrir l'invite de commande et exécuter la commande suivante en remplaçant Pseudo_de_votre_user par le nom de l'utilisateur de votre session : 
> cd "C:\Users\Pseudo_de_votre_user\AppData\Local\Programs\Python\Python310\Scripts"

Ensuite, executer la commande suivante :
> pip install jupyterlab

Une fois l'installation terminée avec succès, vous pouvez lancer JupyterLab avec la commande suivante : 
> jupyter-lab


### Linux & Mac OS

#### Installation Python

Normalement, Python est préinstallé sur la quasi-totalité des distributions. Vous n'avez pas besoin de le réinstaller, mais vous pouvez mettre à jour la version si vous le souhaitez.

Vérifiez la version Python installée en exécutant l'une des deux commandes python suivantes sur votre terminal : 
> python --version   

> python3 --version 

#### Installation Jupyter

Vérifier que la commande pip3 est installée. Sinon, l'installer (exemple pour Debian/Ubuntu/Linux Mint, à adapter selon votre distribution) :

> sudo apt install python3-pip

Ensuite, installer JupyterLab en executant la commande suivante:
> pip3 install -U jupyterlab

Enfin, placez-vous dans votre dossier de travail et lancez un notebook :

> jupyter-lab

## Syntaxe et Concepts de base

In [ ]:
a = 33
b = 9
c = 2.0

In [ ]:
a+b

42

In [ ]:
print(a+b)

42


In [ ]:
type(a)

int

In [ ]:
type(c)

float

In [ ]:
a = 'hello'
type(a)

str

In [ ]:
# Affiche les entiers pairs de 1 à 10
for i in range(1, 11):
    if i % 2 == 0:
        print(i)

2
4
6
8
10


### List

In [ ]:
l = [1,2,3,4,4]
print(l)

[1, 2, 3, 4, 4]


#### len, max, min

In [ ]:
print('longueur de la liste =', len(l))
print("Valeur max de l =", max(l))
print("Valeur min de l =", min(l))

longueur de la liste = 5
Valeur max de l = 4
Valeur min de l = 1


#### Ajout d'un élément d'une liste

In [ ]:
l.append(6)
l

[1, 2, 3, 4, 4, 6]

In [ ]:
l = l+[7]
l

[1, 2, 3, 4, 4, 6, 7]

In [ ]:
l+=[7]
l

[1, 2, 3, 4, 4, 6, 7, 7]

#### Modifier un élément

In [ ]:
l[0] = 29
l

[29, 2, 3, 4, 4, 6, 7, 7]

In [ ]:
l.insert(1,9)
l

[29, 9, 2, 3, 4, 4, 6, 7, 7]

#### Suppression des éléments d'une liste

In [ ]:
l.remove(7)
l

[29, 9, 2, 3, 4, 4, 6, 7]

In [ ]:
l.pop(2)
l

[29, 9, 3, 4, 4, 6, 7]

#### Trier une liste

In [ ]:
l.sort(reverse=True)
print(l)

[29, 9, 7, 6, 4, 4, 3]


In [ ]:
l_sorted = sorted(l)
print('Sorted list:', l_sorted)

Sorted list: [3, 4, 4, 6, 7, 9, 29]


#### Liste non homogène

In [ ]:
l = [1, 'un', 2]
l.append('deux')
l += [3, 'trois']
print(type(l))
l

<class 'list'>


[1, 'un', 2, 'deux', 3, 'trois']

In [ ]:
a = l[3], l[-1]
print(type(a))
a

<class 'tuple'>


('deux', 'trois')

In [ ]:
a[0]

'deux'

In [ ]:
[2**p for p in range(10)] # "Compréhension de liste"

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [ ]:
# Liste des entiers pairs de 1 à 10
l = [i for i in range(1, 11) if i % 2 == 0]
print(l)

[2, 4, 6, 8, 10]


### Tuple

In [ ]:
p = tuple(range(1,5))
print("p=", p)
print("p[0] = ", p[0])

p= (1, 2, 3, 4)
p[0] =  1


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# New section

In [ ]:
p = ([1,2],5)

print(p)

p[0][0] = 8

print(p)

([1, 2], 5)
([8, 2], 5)


In [ ]:
# Les éléments du tuple sont fixes
p[0][0] = 6
p

([6, 2], 5)

In [ ]:
p1 = (1,2)
p2 = (2,1)

print(p1 == p2)

False


### Set

In [ ]:
s = set((1,2,'l'))
print(s)

s = {4,5,9,9,9,9}
print(s)

{1, 2, 'l'}
{9, 4, 5}


In [ ]:
#Ajout d'un élément au set
s.add(6)
print(s)

{9, 4, 5, 6}


In [ ]:
#Suppression d'un élément du set
s.discard(5)
print(s)

{9, 4, 6}


In [ ]:
s.clear()
print(s)

set()


In [ ]:
A = {1,2,3,4,5}
B = {2,4,6,7}
C = {1,2,3}

In [ ]:
#Intersection
print("Intersection de A et B =", A&B)

#Union
print("Union entre A et B =", A|B)

#Exclusion
print("Exclusion de B de A =", A-B)

#Différence symétrique
print("Diff sym. A et B =", A^B)

Intersection de A et B = {2, 4}
Union entre A et B = {1, 2, 3, 4, 5, 6, 7}
Exclusion de B de A = {1, 3, 5}
Diff sym. A et B = {1, 3, 5, 6, 7}


In [ ]:
print("B est inclus strict dans A") if A>B else print(False)
print("C est inclus dans A") if A>=C else print(False)

False
C est inclus dans A


### Dictionary

In [ ]:
# 1ère façon de créer un dictionnaire
dic = {"key1": "value1", "answer": 42}
# 2ème façon de créer un dictionnaire
dic2 = dict(key1="value1", answer=42)
# 3ème façon de créer un dictionnaire
dic3 = dict([("key1","value1"), ("answer",42)])
print(dic)
print(dic2)
print(dic3)

dic["answer"]

{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}


42

In [ ]:
dic['new'] = [1,2,3]

In [ ]:
dic.keys()

dict_keys(['key1', 'answer', 'new'])

In [ ]:
dic.items()

dict_items([('key1', 'value1'), ('answer', 42), ('new', [1, 2, 3])])

In [ ]:
dic.values()

dict_values(['value1', 42, [1, 2, 3]])

In [ ]:
a,b = dic.items()
print(a)

## Programmation Orientée Objet

In [ ]:
"""
Exemple de classe en Python
"""
class Moteur:
    
    # Constructeur
    def __init__(self, esn, panne=False):
        self.esn = esn
        self.panne = panne
    
    # Méthodes
    def dire_bonjour(self):
        print('Bonjour, mon numéro de série est ' + self.esn)
    
    def fonctionne(self):
        return not self.panne 
    

In [ ]:
mot1 = Moteur('420912')
mot2 = Moteur(panne=True, esn='420913')

mot1.dire_bonjour()
print(mot1.fonctionne())

mot1.panne = True
print(mot1.fonctionne())

print('\n')
mot2.dire_bonjour()
print(mot2.fonctionne())

Bonjour, mon numéro de série est 420912
True
False


Bonjour, mon numéro de série est 420913
False


### Méthode récurcive vs Méthode itérative

In [ ]:
# Méthode récursive
def fact1(n):
    if n == 0:
        return 1
    else:
        return n*fact1(n-1)

# Méthode itérative
def fact2(n):
    s=1
    for i in range(1,n+1):
        s*=i
    return s

print(fact1(5))
print(fact2(5))

120
120


In [ ]:
"""
App.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.
"""

'\nApp.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.\n'

In [ ]:
"""
App.1 : Correction
"""

#Méthode itérative
def pgcd1(a,b):
    while (a%b) != 0:
        s = a%b
        a = b
        b = s
    return b


#Méthode récurcive
def pgcd2(a,b):
    if a==b : return a 
    if a<b : a,b = b,a
    return pgcd2(a-b,b)

a = 230
b = 25

print("pgcd de ", a, "et", b, " :")
print("pgcd1(a,b) = ", pgcd1(a,b))
print("pgcd2(a,b) = ", pgcd2(a,b))

pgcd de  230 et 25  :
pgcd1(a,b) =  5
pgcd2(a,b) =  5


## Libraries



```
# This is formatted as code
```

> pip install numpy pandas

> pip3 install -U numpy pandas

### Math

In [ ]:
import math

In [ ]:
x = 4

print("sqrt(x) =", math.sqrt(x))
print("cos(x) =", math.cos(x))
print("sin(x) =", math.sin(x))
print("factorial(x) =", math.factorial(x))

sqrt(x) = 2.0
cos(x) = -0.6536436208636119
sin(x) = -0.7568024953079282
factorial(x) = 24


### Numpy

In [ ]:
import numpy as np

In [ ]:
# Création d'un array à partir d'une liste
v = np.array([1.0, 2.0, 3.0])
# Création d'un array de taille (n,m) initialisé à 0
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Taille d'un array
print(z.shape)
print(v.shape)

(3, 4)
(3,)


In [ ]:
# Opérations courantes
A = np.ones((3,3)) + np.eye(3)
print('A = ', A)
print('Av = ', np.dot(A,v))
print('3*A = ', 3*A)
print('A*v = ', A*v)
print('A + 1 = ', A+1)
print('A + v = ', A+v)
print('A^2 = ', np.square(A))

A =  [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
Av =  [7. 8. 9.]
3*A =  [[6. 3. 3.]
 [3. 6. 3.]
 [3. 3. 6.]]
A*v =  [[2. 2. 3.]
 [1. 4. 3.]
 [1. 2. 6.]]
A + 1 =  [[3. 2. 2.]
 [2. 3. 2.]
 [2. 2. 3.]]
A + v =  [[3. 3. 4.]
 [2. 4. 4.]
 [2. 3. 5.]]
A^2 =  [[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]


In [ ]:
B = np.array([5, 2, 9, 1])

print(np.sort(B))

[1 2 5 9]


#### Compatif de performance : produit matriciel


In [ ]:
import random

In [ ]:
# Création d'une matrice aléatoire sous forme de liste de listes
taille = 2
A = [[random.random() for _ in range(taille)] for _ in range(taille)]

In [ ]:
print(A)

[[0.276484304928418, 0.8266507071553001], [0.45558321926725065, 0.7610062397148172]]


In [ ]:
"""
EXERCICE - Afficher un tuple contenant les dimensions de la matrice A
"""
import numpy as np

# Affichage simple des dimensions de A :
# print tuple(np.shape(A))

# Fonction qui retourne les dim de A :
def Dimension(A) :
  (Long_A,Larg_A) = np.shape(A)
  res = (Long_A, Larg_A)
  return res

print(Dimension(A))


(2, 2)


$$ (AB)_{ij} = \sum_k A_{ik} B_{kj} $$

In [ ]:
"""
EXERCICE - Implémenter le produit matriciel de 2 matrices sous forme de listes python
"""

def produit(A,B) :
  (ligA,colA) = Dimension(A)
  (ligB,colB) = Dimension(B)
  # assert(colA == ligB)
  if (colA == ligB) :
    AB = [[0 for _ in range(ligA)] for _ in range(colB)]
    # print(AB)
    for i in range (ligA) :
      for j in range (colB) :
        for k in range (colA) :
          AB[i][j]  += A[i][k]*B[k][j]
    return AB
  else :
    print("erreur de dimension")

# Test :
A = [ [1, 2, 3] , [3, 4, 5] ]
B = [ [1, 2] , [3, 4] , [5, 6] ]
print("le produit de ", A, "et de ", B, "est : ")
produit(A,B)

le produit de  [[1, 2, 3], [3, 4, 5]] et de  [[1, 2], [3, 4], [5, 6]] est : 


[[22, 28], [40, 52]]

In [ ]:
# Vérification
assert( produit([ [1, 2],[3, 4] ] , [ [1, 2],[3, 4] ] ) == [[7, 10], [15, 22]])

In [ ]:
# test :
A = [ [1, 2, 3] , [3, 4, 5] , [6, 7, 8] ]
print("le produit de ", A, "et de ", A, "est : ")
print(produit(A, A))

le produit de  [[1, 2, 3], [3, 4, 5], [6, 7, 8]] et de  [[1, 2, 3], [3, 4, 5], [6, 7, 8]] est : 
[[25, 31, 37], [45, 57, 69], [75, 96, 117]]


In [ ]:
# test erreur :
B = [ [1, 2, 3] , [3, 4, 5] ]
print("le produit de ", A, "et de ", B, "est : ")
print('test erreur de dimension :', produit(B, B))

le produit de  [[1, 2, 3], [3, 4, 5], [6, 7, 8]] et de  [[1, 2, 3], [3, 4, 5]] est : 
erreur de dimension
test erreur de dimension : None


In [ ]:
# Sortons le chronomètre
%timeit produit(A, A)

21.9 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# Et maintenant, avec numpy !
import numpy as np

In [ ]:
A2 = np.array(A)
print(A2)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [ ]:
%timeit np.dot(A, A)

10.5 µs ± 431 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


EXERCICE - Remplissez le tableau suivant avec les durées d'exécution constatées :

(Conseil : pour la taille 3000, essayez UNIQUEMENT avec numpy)

Taille | Python | numpy
-------|--------|-------
30     | 5.53 ms ± 92.6 µs    | 179 µs ± 3.5 µs
300    | 5.56 s ± 206 ms      | 20 ms ± 436 µs
3000   | + 5 min 21 s         | 2.46 s ± 75.6 ms 

In [ ]:

## CE PROGRAMME PEUT METTRE DU TEMPS A TOURNER

# Création d'une matrice aléatoire sous forme de liste de listes
for N in [30, 300, 3000] :
  A = [[random.random() for _ in range(N)] for _ in range(N)]
  B = [[random.random() for _ in range(N)] for _ in range(N)]
  print("time pour N = ", N, " :")
  print("avec numpy :")
  %timeit np.dot(A, B)
  print("avec python :")
  %timeit produit(A, B)
# Pour N = 3000 avec python, le produit matriciel prend trop de temps (> 20 min)

###  Pandas

In [ ]:
import pandas as pd

In [ ]:
df_exemple = pd.DataFrame({"ESN": ["E420912", "E420913", "E420914"], "panne": [False, False, True]})
df_exemple

ESN  panne
0  E420912  False
1  E420913  False
2  E420914   True

#### Lecture et prétraitement de données


In [ ]:
!git clone https://github.com/MadaneA/MACS3-Statistiques-Descriptives-TDs.git

Cloning into 'MACS3-Statistiques-Descriptives-TDs'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 52 (delta 7), reused 50 (delta 5), pack-reused 0
Unpacking objects: 100% (52/52), done.


In [ ]:
import os
os.chdir('MACS3-Statistiques-Descriptives-TDs')

In [ ]:
# Chargement d'un fichier CSV ou Excel
df = pd.read_csv("./data/Vol010.csv")
# Affichage des 5 premières lignes
df.head()

t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
0                  datenum   deg_C          _       _        %        %   
1  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1 VIB_CN2  \
0      %     %_RPM   psi        _  ...       _      _     DEG       _       _   
1    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
2    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
3    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
4    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   

  VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
0       _       _     DEG     lb/h  mach  
1     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN      NaN   NaN  
4     NaN     NaN     NaN  7679.98  0.15  

[5 rows x 26 columns]

In [ ]:
df.loc[0]

t             datenum
EGT_SEL         deg_C
FLIGHT_MOD          _
FMV_SEL             _
HPTC_SEL            %
LPTC_SEL            %
N1_SEL              %
N2_ACTSEL       %_RPM
OIL_P             psi
OIL_TEMP            _
PS3_SEL           psi
PT2_SEL            mb
P0_SEL            psi
TAT             deg_C
TBV_SEL             %
TRA_SEL           DEG
T25_SEL             _
T3_SEL              _
VBV_SEL           DEG
VIB_CN1             _
VIB_CN2             _
VIB_TN1             _
VIB_TN2             _
VSV_SEL           DEG
WFM_SEL          lb/h
XM               mach
Name: 0, dtype: object

In [ ]:
"""
EXERCICE - Dimensions d'un DataFrame
Affichez le nombre de colonnes et de ligne du DataFrame (indice : beaucoup de méthodes sont communes entre numpy et pandas)
"""
# raise NotImplementedError
(Col, Ligne) = df.shape
print('Nombre de colonnes :', Col)
print('Nombre de lignes :', Ligne)
print('Dimension de df :', df.ndim)

Nombre de colonnes : 22945
Nombre de lignes : 26
Dimension de df : 2


In [ ]:
df.size, len(df)

(596570, 22945)

In [ ]:
df.columns

Index(['t', 'EGT_SEL', 'FLIGHT_MOD', 'FMV_SEL', 'HPTC_SEL', 'LPTC_SEL',
       'N1_SEL', 'N2_ACTSEL', 'OIL_P', 'OIL_TEMP', 'PS3_SEL', 'PT2_SEL',
       'P0_SEL', 'TAT', 'TBV_SEL', 'TRA_SEL', 'T25_SEL', 'T3_SEL', 'VBV_SEL',
       'VIB_CN1', 'VIB_CN2', 'VIB_TN1', 'VIB_TN2', 'VSV_SEL', 'WFM_SEL', 'XM'],
      dtype='object')

Les colonnes des DF sont typées, à la manière d'une base de données relationnelle, contrairement aux variables python classiques. Les types des colonnes sont accessibles via df.dtypes. Les principaux types sont les numériques (int32, int64, float etc.

In [ ]:
df.loc[10:15, ['EGT_SEL', 'FLIGHT_MOD']]

EGT_SEL FLIGHT_MOD
10    0.00234327        NaN
11  1.08032e-007        NaN
12  3.12514e-012        NaN
13             0        NaN
14       72.0006        NaN
15       215.996        NaN

In [ ]:
"""
EXERCICE - Extraction et suppression des unités
On remarque que la 1ère ligne ne contient pas de données mais les unités de chaque colonne.
Pour la suite des traitements, il faut supprimer cette ligne. On souhaite toutefois garder l'information des unités de chaque colonne.
1. Récupérez les unités et stockez les dans une structure adaptée.
2. Supprimez cette ligne du DataFrame en utilisant la méthode "drop"
"""
unite = df.iloc[0]
df = df.drop(0)
df.head()

t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
1  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   
5  15/09/2011 14:25:59.125     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL    OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1  \
1    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
2    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
3    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
4    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
5      0         0  647.998      NaN  ...     NaN    NaN       0       0   

  VIB_CN2 VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
1     NaN     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN     NaN      NaN   NaN  
4     NaN     NaN     NaN     NaN  7679.98  0.15  
5       0       0       0       0  4607.86  0.15  

[5 rows x 26 columns]

In [ ]:
print(unite)


t             datenum
EGT_SEL         deg_C
FLIGHT_MOD          _
FMV_SEL             _
HPTC_SEL            %
LPTC_SEL            %
N1_SEL              %
N2_ACTSEL       %_RPM
OIL_P             psi
OIL_TEMP            _
PS3_SEL           psi
PT2_SEL            mb
P0_SEL            psi
TAT             deg_C
TBV_SEL             %
TRA_SEL           DEG
T25_SEL             _
T3_SEL              _
VBV_SEL           DEG
VIB_CN1             _
VIB_CN2             _
VIB_TN1             _
VIB_TN2             _
VSV_SEL           DEG
WFM_SEL          lb/h
XM               mach
Name: 0, dtype: object


On remarque que toutes les colonnes ont été reconnues comme de type object, c'est-à-dire des chaînes de caractères, alors que ce sont des valeurs numériques. Cela est dû à la première ligne contenant les unités. Il faut donc convertir les colonnes en numérique. La colonne 't', quant à elle, doit être convertie en type datetime.

In [ ]:
df['t'] = pd.to_datetime(df['t'])
df[df.columns[1:]] = df[df.columns[1:]].apply(pd.to_numeric)

In [ ]:
df.dtypes

t             datetime64[ns]
EGT_SEL              float64
FLIGHT_MOD           float64
FMV_SEL              float64
HPTC_SEL             float64
LPTC_SEL             float64
N1_SEL               float64
N2_ACTSEL            float64
OIL_P                float64
OIL_TEMP             float64
PS3_SEL              float64
PT2_SEL              float64
P0_SEL               float64
TAT                  float64
TBV_SEL              float64
TRA_SEL              float64
T25_SEL              float64
T3_SEL               float64
VBV_SEL              float64
VIB_CN1              float64
VIB_CN2              float64
VIB_TN1              float64
VIB_TN2              float64
VSV_SEL              float64
WFM_SEL              float64
XM                   float64
dtype: object

In [ ]:
"""
Exercice - Index temporel
Comme nos données sont une série temporelle multivariée, on souhaite utiliser un index temporel.
1. Créez une copie de df, appelée df2, à l'aide de la méthode du même nom.
2. Affectez la colonne du temps ('t') en tant qu'indice du DataFrame.
3. Supprimez la colonne 't' du DF résultant.
"""

# Question 1 :
df2 = df.copy()
# Question 2 :
df2.set_index('t')
# Question 3 :
del df2['t']
print(df2)

       EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  N1_SEL  N2_ACTSEL  \
1          NaN         NaN      NaN       NaN       NaN     NaN        0.0   
2          NaN         NaN      NaN       NaN       NaN     NaN        0.0   
3          NaN         NaN      NaN       NaN       NaN     NaN        0.0   
4          NaN         NaN      NaN       NaN       NaN     NaN        0.0   
5          NaN         NaN      NaN       NaN       NaN     0.0        0.0   
...        ...         ...      ...       ...       ...     ...        ...   
22940      NaN         NaN      NaN       NaN       NaN     NaN        NaN   
22941      NaN         NaN      NaN       NaN       NaN     NaN        NaN   
22942      NaN         NaN      NaN       NaN       NaN     NaN        NaN   
22943      NaN         NaN      NaN       NaN       NaN     NaN        NaN   
22944      NaN         NaN      NaN       NaN       NaN     NaN        NaN   

         OIL_P  OIL_TEMP  PS3_SEL  ...  T25_SEL  T3_SEL  VBV_SE

On constate que pandas a automatiquement reconnu un DatetimeIndex, adapté pour des manipulations de séries temporelles (moyennes glissantes, etc) !

### Valeurs manquantes

**NaN = Not a Number**

Les valeurs NaN doivent être éliminées ou imputées (i.e. remplacées par une certaine valeur) avant la suite des traitements. Ce choix dépend du cas d'usage. Dans un premier temps, nous allons apprendre à :

* trouver les données manquantes (méthode `isna`)
* éliminer les données manquantes d'un DataFrame (méthode `dropna`)
* les remplacer par une constante (méthode (`fillna`)

In [ ]:
"""
EXERCICE - La méthode isna
1. Testez la méthode isna sur le DataFrame df2, puis sur une colonne ou une ligne. Que renvoie-t-elle ?
2. En appliquant les méthodes any(axis=...), mean() et max()/idxmax() sur les résultats de isna(), répondez aux questions suivantes :
    2.1 Quelles colonnes contiennent des valeurs manquantes, lesquelles n'en contiennent pas ?
    2.2 Quel est le pourcentage de valeurs manquantes dans le DF (a) par colonne (b) globalement ? Quelle variable contient le plus de NaN ?
    2.3 Quel est le pourcentage d'indices du DF pour lesquels toutes les variables sont présentes ?
"""

print('Question 1')
df2.isna().head()

Question 1


EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  N1_SEL  N2_ACTSEL  OIL_P  \
1     True        True     True      True      True    True      False   True   
2     True        True     True      True      True    True      False   True   
3     True        True     True      True      True    True      False   True   
4     True        True     True      True      True    True      False   True   
5     True        True     True      True      True   False      False  False   

   OIL_TEMP  PS3_SEL  ...  T25_SEL  T3_SEL  VBV_SEL  VIB_CN1  VIB_CN2  \
1      True     True  ...     True    True     True     True     True   
2      True     True  ...     True    True     True     True     True   
3      True     True  ...     True    True     True     True     True   
4      True     True  ...     True    True     True     True     True   
5      True    False  ...     True    True    False    False    False   

   VIB_TN1  VIB_TN2  VSV_SEL  WFM_SEL     XM  
1     True     True     True     True   True  
2     True     True     True     True   True  
3     True     True     True     True   True  
4     True     True     True    False  False  
5    False    False    False    False  False  

[5 rows x 25 columns]

In [ ]:
print(df2['FMV_SEL'].isna())

1        True
2        True
3        True
4        True
5        True
         ... 
22940    True
22941    True
22942    True
22943    True
22944    True
Name: FMV_SEL, Length: 22944, dtype: bool


In [ ]:
# la 1ier ligne :
print(df2.loc[1].isna())

EGT_SEL        True
FLIGHT_MOD     True
FMV_SEL        True
HPTC_SEL       True
LPTC_SEL       True
N1_SEL         True
N2_ACTSEL     False
OIL_P          True
OIL_TEMP       True
PS3_SEL        True
PT2_SEL        True
P0_SEL         True
TAT            True
TBV_SEL        True
TRA_SEL        True
T25_SEL        True
T3_SEL         True
VBV_SEL        True
VIB_CN1        True
VIB_CN2        True
VIB_TN1        True
VIB_TN2        True
VSV_SEL        True
WFM_SEL        True
XM             True
Name: 1, dtype: bool


In [ ]:
print('Question 2.1')
print(df2.isna().any(axis = 'index'))

Question 2.1
EGT_SEL       True
FLIGHT_MOD    True
FMV_SEL       True
HPTC_SEL      True
LPTC_SEL      True
N1_SEL        True
N2_ACTSEL     True
OIL_P         True
OIL_TEMP      True
PS3_SEL       True
PT2_SEL       True
P0_SEL        True
TAT           True
TBV_SEL       True
TRA_SEL       True
T25_SEL       True
T3_SEL        True
VBV_SEL       True
VIB_CN1       True
VIB_CN2       True
VIB_TN1       True
VIB_TN2       True
VSV_SEL       True
WFM_SEL       True
XM            True
dtype: bool


In [ ]:
print('Question 2.2.a')
ptr = df2.isna().mean()*100
print(ptr)

Question 2.2.a
EGT_SEL       0.348675
FLIGHT_MOD    0.444561
FMV_SEL       0.444561
HPTC_SEL      0.422768
LPTC_SEL      0.457636
N1_SEL        0.418410
N2_ACTSEL     0.252789
OIL_P         0.379184
OIL_TEMP      0.383543
PS3_SEL       0.300732
PT2_SEL       0.370467
P0_SEL        0.370467
TAT           0.300732
TBV_SEL       0.296374
TRA_SEL       0.300732
T25_SEL       0.470711
T3_SEL        0.470711
VBV_SEL       0.292015
VIB_CN1       0.292015
VIB_CN2       0.283298
VIB_TN1       0.283298
VIB_TN2       0.283298
VSV_SEL       0.274582
WFM_SEL       0.270223
XM            0.261506
dtype: float64


In [ ]:
print('Question 2.2.b')
print(ptr.mean(), '%')

Question 2.2.b
0.34693165969316603 %


In [ ]:
print('Question 2.2 - Max NaN')
df3 = df2.isna().sum()
print(df3)
print(" ")
print("le max est :")
for i in range(len(df3)):
  if df3[i] == max(df3) :
    print(df3.index[i])
print("et est atteint en ", max(df3))

Question 2.2 - Max NaN
EGT_SEL        80
FLIGHT_MOD    102
FMV_SEL       102
HPTC_SEL       97
LPTC_SEL      105
N1_SEL         96
N2_ACTSEL      58
OIL_P          87
OIL_TEMP       88
PS3_SEL        69
PT2_SEL        85
P0_SEL         85
TAT            69
TBV_SEL        68
TRA_SEL        69
T25_SEL       108
T3_SEL        108
VBV_SEL        67
VIB_CN1        67
VIB_CN2        65
VIB_TN1        65
VIB_TN2        65
VSV_SEL        63
WFM_SEL        62
XM             60
dtype: int64
 
le max est :
T25_SEL
T3_SEL
et est atteint en  108


In [ ]:
print('Question 2.3')
sum = df2.isna().sum(axis = 1)
# print(sum)

counter = 0
for i in sum.loc[:] :
    if(i == 0) :
        counter = counter + 1

nb_row = df2.shape[0]
print((counter/nb_row)*100,"%")

Question 2.3
99.48134588563458 %


In [ ]:
"""
EXERCICE - La méthode dropna
La méthode dropna permet d'éliminer les valeurs manquantes (NaN). Lisez d'abord sa documentation.
1. À quoi correspondent les arguments "axis" et "how" ?
2. Éliminez toutes les lignes contenant uniquement des valeurs manquantes.
3. Éliminez toutes les lignes contenant au moins une valeur manquante. Combien y a-t-il de lignes de différence ?
4. Éliminez toutes les colonnes contenant au moins une valeur manquante.
"""

# Question 1
"""
Dans dropna :
- dropna supprime soit la ligne si axis = 0 soit les colones si axis = 1

       |0 pour désigner les lignes
axis = |
       |1 pour désigner les colones

- how {‘any’, ‘all’}, déterminer si la ligne ou la colonne est supprimée de DataFrame,
  -> any : si au moins une valeur est NA.
  -> all : si toutes les valeurs sont NA.

"""


In [ ]:
# Question 2 :
print(df2.dropna(how = 'all', axis = 'index'))

       EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  N1_SEL  N2_ACTSEL  \
1          NaN         NaN      NaN       NaN       NaN     NaN        0.0   
2          NaN         NaN      NaN       NaN       NaN     NaN        0.0   
3          NaN         NaN      NaN       NaN       NaN     NaN        0.0   
4          NaN         NaN      NaN       NaN       NaN     NaN        0.0   
5          NaN         NaN      NaN       NaN       NaN     0.0        0.0   
...        ...         ...      ...       ...       ...     ...        ...   
22903      NaN         NaN      NaN       NaN       NaN     NaN        0.0   
22904      NaN         NaN      NaN       NaN       NaN     NaN        0.0   
22905      NaN         NaN      NaN       NaN       NaN     NaN        NaN   
22906      NaN         NaN      NaN       NaN       NaN     NaN        NaN   
22907      NaN         NaN      NaN       NaN       NaN     NaN        NaN   

         OIL_P  OIL_TEMP  PS3_SEL  ...  T25_SEL  T3_SEL  VBV_SE

In [ ]:
# Question 3 :
print(df2.dropna(how = 'any', axis = 'index'))

        EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  N1_SEL  N2_ACTSEL  \
20     335.9840         1.0    0.000       0.0       0.0     0.0        0.0   
21     239.9860         1.0    0.000       0.0       0.0     0.0        0.0   
22     167.9910         1.0    0.000       0.0       0.0     0.0        0.0   
23     119.9940         1.0    0.000       0.0       0.0     0.0        0.0   
24      72.0011         1.0    0.000       0.0       0.0     0.0        0.0   
...         ...         ...      ...       ...       ...     ...        ...   
22888  230.8250         1.0  -12.375       0.0       0.0     0.0        0.0   
22889  137.4770         1.0  -12.375       0.0       0.0     0.0        0.0   
22890  113.4530         1.0  -12.375       0.0       0.0     0.0        0.0   
22891  158.8080         1.0  -12.375       0.0       0.0     0.0        0.0   
22892  204.1800         1.0  -12.375       0.0       0.0     0.0        0.0   

       OIL_P  OIL_TEMP    PS3_SEL  ...  T25_SEL  T3

In [ ]:
nb_all = df2.dropna(how = 'all', axis = 'index').shape[0]
nb_any = df2.dropna(how = 'any', axis = 'index').shape[0]
nb_dif = nb_all - nb_any
print('Le nombre de lignes de différence est:', nb_dif)

Le nombre de lignes de différence est: 64


In [ ]:
# Question 4 :
print(df2.dropna(how = 'any', axis = 'columns'))

" On voit donc qu'il ne reste plus aucune colonne "

Empty DataFrame
Columns: []
Index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, ...]

[22944 rows x 0 columns]


In [ ]:
"""
EXERCICE - La méthode fillna
La méthode dropna permet d'imputer les valeurs manquantes (NaN). Lisez d'abord sa documentation.
1. Quelles sont les différentes stratégies de remplissage des valeurs manquantes ?
  -> dropna() gère et supprime les valeurs Null d’un bloc de données,
  -> fillna() gère et laisse l’utilisateur remplacer les valeurs NaN par une valeur qui lui est propre.
  
2. Imputez les valeurs manquantes de la colonne age du DF donné en exemple par :
    - 0
    - la dernière valeur précédente/suivante valide
    - la moyenne
    - la valeur la plus courante (mode)
3. Quel est le meilleur choix dans ce cas ? Et pour le cas d'une variable temporelle, par exemple la température 'EGT_SEL' de notre jeu de données ?
"""
exemple = pd.DataFrame({'nom': ['Alice', 'Bob', 'Charlie', 'David'], 'age': [24, pd.np.nan, 99, 24]})
exemple

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  from ipykernel import kernelapp as app


nom   age
0    Alice  24.0
1      Bob   NaN
2  Charlie  99.0
3    David  24.0

In [ ]:
# Question 2.1 :
exemple.fillna(0)

nom   age
0    Alice  24.0
1      Bob   0.0
2  Charlie  99.0
3    David  24.0

In [ ]:
# Question 2.2 :
exemple.fillna(method = "ffill")

nom   age
0    Alice  24.0
1      Bob  24.0
2  Charlie  99.0
3    David  24.0

In [ ]:
# Question 2.3 :
moy = exemple.loc[:,'age'].mean()
exemple.fillna(moy)

nom   age
0    Alice  24.0
1      Bob  49.0
2  Charlie  99.0
3    David  24.0

In [ ]:
# Question 2.4 :
m = exemple.loc[:,'age'].mode()  
exemple.fillna(m)

nom   age
0    Alice  24.0
1      Bob   NaN
2  Charlie  99.0
3    David  24.0

## Git

Créer un compte GitHub : https://github.com/

Créer un nouveau repository :
1. Sélectionner "Nouveau dépôt" dans le menu déroulant avec le signe +. 
2. Saisisser un nom pour votre dépôt (par exemple, "TDs statistiques descriptives") 
3. Cliquer sur "Créer un dépôt". Ne vous souciez pas des autres options.



Télécharger Git Bash : https://git-scm.com/downloads

Sur Git Bash, positionnez-vous dans le répertoire où votre projet figure.

Ensuite

> git init

> git remote add origin https://github.com/********

> git add .

> git commit -m "Ajout du TD1"

> git push origin master

C'est tout ! Vous avez créé votre repo GitHub ! 